ALTER TABLE "Package" ADD COLUMN IF NOT EXISTS "highlight" TEXT;
ALTER TABLE "Package" ADD COLUMN IF NOT EXISTS "featuresEn" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Package" ADD COLUMN IF NOT EXISTS "featuresMy" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
